// Generated by CoffeeScript 1.3.3
(function() {
  var isSamsung,
    __slice = [].slice;

  isSamsung = /maple/i.test(navigator.userAgent);

  if (isSamsung) {
    this.console = {
      log: function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return alert(args);
      }
    };
    document.write("<script type='text/javascript' src='$MANAGER_WIDGET/Common/API/Widget.js'></script>\n<script type='text/javascript' src='$MANAGER_WIDGET/Common/API/TVKeyValue.js'></script>");
    window.onload = function() {
      var keys;
      keys = new Common.API.TVKeyValue();
      this.VK_LEFT = keys.KEY_LEFT;
      this.VK_RIGHT = keys.KEY_RIGHT;
      this.VK_UP = keys.KEY_UP;
      return this.VK_DOWN = keys.KEY_DOWN;
    };
  }

}).call(this);
